### ISSUE TITLE
Participate in MSU Annual Video Codecs Comparison 2019

### ISSUE THREAD

**Issue by EwoutH** [divideon/xvc#12]
Moscow State University is soon starting with it's yearly codec review, it would be a great chance to demonstrate xvc's performance.
- [MSU Annual Video Codecs Comparison 2019: Call for codecs](http://www.compression.ru/video/codec_comparison/call_for_codecs_19.html)

**Comment by jonatansamuelsson** [comment]
Thanks for the suggestion. We are already signed up to MSU's video codec comparison.
