### ISSUE TITLE
What's the command for image compression?

### ISSUE THREAD

**Issue by limuhit** [divideon/xvc#13]
Could you offer the specific commands for image compression including encoding and decoding? I am trying to explore the xvc with image compression but fail to get the correct decoding results.

**Comment by jonatansamuelsson** [comment]
The xvc encoder operates on uncompressed videos/images in yuv or y4m format.

If your image is in y4m format you can for example use the following command to encode:
`xvcenc -input-file test.y4m -output-file enc.xvc -qp 28`
and this command to decode:
`xvcdec -bitstream-file enc.xvc -output-file dec.y4m`

If your image is in a different format e.g. png you can use an external application to convert it before encoding, or piping it directly to the encoder, for example using ffmpeg:
`ffmpeg -i test.png -pix_fmt yuv420p10le -strict -1 -f yuv4mpegpipe - | xvcenc -input-file - -output-file enc.xvc -qp 28`
and to decode and convert back to png:
`xvcdec -bitstream-file enc.xvc -output-file - | ffmpeg -i - dec.png`

**Comment by limuhit** [comment]
Thanks a lot.
