### ISSUE TITLE
Parameters min/max values?

### ISSUE THREAD

**Issue by Selur** [divideon/xvc#2]
What are the min&max values for the parameters?
  -input-width <int>
  -input-height <int>
  -input-bitdepth <int>
  -internal-bitdepth <int>
  -framerate <float>
  -skip-pictures <int>
  -temporal-subsample <int>
  -max-pictures <int>
  -sub-gop-length <int>
  -max-keypic-distance <int>
  -closed-gop <int>
  -num-ref-pics <int>
  -deblock <0/1>
  -beta-offset <int>
  -tc-offset <int>
  -qp <int>

**Comment by jonatansamuelsson** [comment]
Min and max values for parameters added in 62c3004249f7c43f81cf9d28400fd43fe9e23c08
