### ISSUE TITLE
Mobile Build Instructions

### ISSUE THREAD

**Issue by ohenepee** [divideon/xvc#5]
Can you please provide build instructions for Android & iOS?

**Comment by perher** [comment]
xvc is only a library and needs to be integrated with a video player before it can run on either Android or iOS. Documenting general mobile development instructions is out of scope for this project, but see for example how to get started with VLC on these pages:
https://wiki.videolan.org/AndroidCompile/
https://wiki.videolan.org/IOSCompile/
