### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by tanersener** [divideon/xvc#6]
According to `CMakeLists.txt`, I have two options to enable `arm` support.

1. Set `CMAKE_SYSTEM_PROCESSOR`
2. Set `XVC_TARGET_ARCH`

But both options are not complete to build `xvc` on all Android `arm` platforms. 

1. Setting `CMAKE_SYSTEM_PROCESSOR` supports only `armv7`.
    - Newer `armv8a` aka `arm64` is not supported.
    - Enabling `armv7`, also enables `NEON` support, but all `armv7` platforms does not have `NEON` extension as mentioned [here](https://developer.android.com/ndk/guides/cpu-arm-neon).

2. Setting `XVC_TARGET_ARCH` supports `arm`, `arm64` and `armv7` variants. But again they enables `NEON` support for all of them. Which is not correct for `armv7`.

Additionally, it is not possible to manually set `NEON` support. You don't have to allow it, but if there was an option for it, user would decide to support it or not.

Is it possible to update `CMakeLists.txt` according to the issues above?

**Comment by perher** [comment]
In general when building on Android the preferred method is setting `XVC_TARGET_ARCH=$ANDROID_ABI`. As you say `NEON` is always enabled for `armv7` at compile time but then also checked at run-time for if there is hardware support.

Do you get compilation problems for `armv7`?

**Comment by tanersener** [comment]
No, I don't get any problems. Actually I wasn't expecting a hardware check at runtime. Most libraries don't do that, kudos to you. 

How about documenting this behaviour?

**Comment by perher** [comment]
Cool, yeah better documentation is on the roadmap. Feel free to reach out if you have any feedback on testing xvc at info@divideon.com.
